Repository Decathlon/vitamin-compose, pull requests merged in 2023-01, with the labels that each got.

#73 config: update CODEOWNERS
  .github/CODEOWNERS
Labels: config 🛠

#71 fix(buttons): large ButtonSizes height
  buttons/src/main/java/com/decathlon/vitamin/compose/buttons/VitaminButtonsSizes.kt
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Conversion,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Conversion,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Ghost,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Ghost,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[GhostReversed,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[GhostReversed,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Primary,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Primary,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[PrimaryReversed,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[PrimaryReversed,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Secondary,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Secondary,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Tertiary,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_large[Tertiary,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_medium[Conversion,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_medium[Conversion,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_medium[Primary,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_medium[Primary,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_medium[PrimaryReversed,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_medium[Secondary,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_medium[Secondary,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_medium[Tertiary,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminButtonsPrimaryTest_medium[Tertiary,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminIconButtonsPrimaryTest_medium[Conversion,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminIconButtonsPrimaryTest_medium[Conversion,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminIconButtonsPrimaryTest_medium[Primary,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminIconButtonsPrimaryTest_medium[Primary,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminIconButtonsPrimaryTest_medium[PrimaryReversed,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminIconButtonsPrimaryTest_medium[Secondary,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminIconButtonsPrimaryTest_medium[Secondary,Light].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminIconButtonsPrimaryTest_medium[Tertiary,Dark].png
  buttons/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminIconButtonsPrimaryTest_medium[Tertiary,Light].png
Labels: enhancement 🚀, run 💨

#67 feat(Progress): Add extra small size
  progressbars/build.gradle.kts
  progressbars/src/main/java/com/decathlon/vitamin/compose/progressbars/VitaminCircularProgressBarSizes.kt
  progressbars/src/test/kotlin/com/decathlon/vitamin/compose/buttons/VitaminCircularProgressPrimaryTest.kt
  progressbars/src/test/kotlin/com/decathlon/vitamin/compose/buttons/VitaminLinearProgressPrimaryTest.kt
  progressbars/src/test/kotlin/com/decathlon/vitamin/compose/buttons/utils/ProgressVariantsFactory.kt
  progressbars/src/test/kotlin/com/decathlon/vitamin/compose/buttons/utils/Theme.kt
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminCircularProgressPrimaryTest_extraSmall[Dark].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminCircularProgressPrimaryTest_extraSmall[Light].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminCircularProgressPrimaryTest_medium[Dark].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminCircularProgressPrimaryTest_medium[Light].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminCircularProgressPrimaryTest_small[Dark].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminCircularProgressPrimaryTest_small[Light].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminLinearProgressPrimaryTest_large[Dark].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminLinearProgressPrimaryTest_large[Light].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminLinearProgressPrimaryTest_medium[Dark].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminLinearProgressPrimaryTest_medium[Light].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminLinearProgressPrimaryTest_small[Dark].png
  progressbars/src/test/snapshots/images/com.decathlon.vitamin.compose.buttons_VitaminLinearProgressPrimaryTest_small[Light].png
  sample/src/main/java/com/decathlon/compose/sample/screens/Progress.kt
Labels: enhancement 🚀, run 💨

#64 Create small variant size for tags
  sample/src/main/java/com/decathlon/compose/sample/screens/Tags.kt
  tags/build.gradle.kts
  tags/src/main/java/com/decathlon/vitamin/compose/tags/VitaminTagSizes.kt
  tags/src/test/kotlin/com/decathlon/vitamin/compose/tags/VitaminTagsTest.kt
  tags/src/test/kotlin/com/decathlon/vitamin/compose/tags/utils/Theme.kt
  tags/src/test/kotlin/com/decathlon/vitamin/compose/tags/utils/Variant.kt
  tags/src/test/snapshots/images/com.decathlon.vitamin.compose.tags_VitaminTagsTest_medium[Default,Dark].png
  tags/src/test/snapshots/images/com.decathlon.vitamin.compose.tags_VitaminTagsTest_medium[Default,Light].png
  tags/src/test/snapshots/images/com.decathlon.vitamin.compose.tags_VitaminTagsTest_medium[Interactive,Dark].png
  tags/src/test/snapshots/images/com.decathlon.vitamin.compose.tags_VitaminTagsTest_medium[Interactive,Light].png
  tags/src/test/snapshots/images/com.decathlon.vitamin.compose.tags_VitaminTagsTest_small[Default,Dark].png
  tags/src/test/snapshots/images/com.decathlon.vitamin.compose.tags_VitaminTagsTest_small[Default,Light].png
  tags/src/test/snapshots/images/com.decathlon.vitamin.compose.tags_VitaminTagsTest_small[Interactive,Dark].png
  tags/src/test/snapshots/images/com.decathlon.vitamin.compose.tags_VitaminTagsTest_small[Interactive,Light].png
Labels: enhancement 🚀, run 💨

#60 feat(Fab): add fab and fab extended components
  fabs/.gitignore
  fabs/README.txt
  fabs/build.gradle.kts
  fabs/gradle.properties
  fabs/src/main/AndroidManifest.xml
  fabs/src/main/java/com/decathlon/vitamin/compose/fabs/NoRippleInteractionSource.kt
  fabs/src/main/java/com/decathlon/vitamin/compose/fabs/VitaminFabExtendedSizes.kt
  fabs/src/main/java/com/decathlon/vitamin/compose/fabs/VitaminFabSizes.kt
  fabs/src/main/java/com/decathlon/vitamin/compose/fabs/VitaminFabs.kt
  fabs/src/main/java/com/decathlon/vitamin/compose/fabs/VitaminFabsColors.kt
  fabs/src/main/java/com/decathlon/vitamin/compose/fabs/VitaminFabsExtended.kt
  fabs/src/test/kotlin/com/decathlon/vitamin/compose/fabs/VitaminFabsExtendedPrimaryTest.kt
  fabs/src/test/kotlin/com/decathlon/vitamin/compose/fabs/VitaminFabsPrimaryTest.kt
  fabs/src/test/kotlin/com/decathlon/vitamin/compose/fabs/utils/FabVariantsFactory.kt
  fabs/src/test/kotlin/com/decathlon/vitamin/compose/fabs/utils/Theme.kt
  fabs/src/test/kotlin/com/decathlon/vitamin/compose/fabs/utils/Variant.kt
  fabs/src/test/snapshots/images/com.decathlon.vitamin.compose.fabs_VitaminFabsExtendedPrimaryTest_default[Primary,Dark].png
  fabs/src/test/snapshots/images/com.decathlon.vitamin.compose.fabs_VitaminFabsExtendedPrimaryTest_default[Primary,Light].png
  fabs/src/test/snapshots/images/com.decathlon.vitamin.compose.fabs_VitaminFabsPrimaryTest_default[Primary,Dark].png
  fabs/src/test/snapshots/images/com.decathlon.vitamin.compose.fabs_VitaminFabsPrimaryTest_default[Primary,Light].png
  fabs/src/test/snapshots/images/com.decathlon.vitamin.compose.fabs_VitaminFabsPrimaryTest_mini[Primary,Dark].png
  fabs/src/test/snapshots/images/com.decathlon.vitamin.compose.fabs_VitaminFabsPrimaryTest_mini[Primary,Light].png
  sample/src/main/java/com/decathlon/compose/sample/MainActivity.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Fabs.kt
  settings.gradle.kts
  vitamin/build.gradle.kts
Labels: enhancement 🚀, build 🏗

#74 chore: Update Vitamin Android version to 0.5.0-beta01
  versions.properties
Labels: icons ✨, run 💨

#70 feat(quantity): remove component fixed size
  quantity-pickers/README.md
  quantity-pickers/src/main/java/com/decathlon/vitamin/compose/quantity/pickers/VitaminQuantityPickers.kt
  quantity-pickers/src/main/java/com/decathlon/vitamin/compose/quantity/pickers/internals/MiddleTextField.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/QuantityPicker.kt
Labels: enhancement 🚀, run 💨

#75 chore: Upgrade libraries versions.
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/decathlon/vitamin/compose/Versions.kt
  gradle/wrapper/gradle-wrapper.properties
  versions.properties
Labels: config 🛠

#76 fix(buttons): Fix Ripple Theme on Buttons
  buttons/src/main/java/com/decathlon/vitamin/compose/buttons/VitaminButtons.kt
  buttons/src/main/java/com/decathlon/vitamin/compose/buttons/VitaminIconButtons.kt
Labels: bug 🐛, run 💨

#78 feat(tabs): manage tabItems size
  tabs/README.md
  tabs/src/main/java/com/decathlon/vitamin/compose/tabs/VitaminTabs.kt
Labels: run 💨
