Repository Decathlon/vitamin-compose, pull requests merged in 2023-04, with the labels that each got.

#128 docs(contributing.md): fix typo
  CONTRIBUTING.md
Labels: documentation 📚, run 💨

#109 feat(quantity-pickers): Add error message label
  quantity-pickers/README.md
  quantity-pickers/build.gradle.kts
  quantity-pickers/src/main/java/com/decathlon/vitamin/compose/quantity/pickers/VitaminQuantitiesColors.kt
  quantity-pickers/src/main/java/com/decathlon/vitamin/compose/quantity/pickers/VitaminQuantitiesSizes.kt
  quantity-pickers/src/main/java/com/decathlon/vitamin/compose/quantity/pickers/VitaminQuantityPickers.kt
  quantity-pickers/src/main/java/com/decathlon/vitamin/compose/quantity/pickers/internals/HelperText.kt
  quantity-pickers/src/main/java/com/decathlon/vitamin/compose/quantity/pickers/internals/Picker.kt
  quantity-pickers/src/main/res/values/strings.xml
  quantity-pickers/src/test/kotlin/com/decathlon/vitamin/compose/quantity/pickers/VitaminQuantityPickersPrimaryTest.kt
  quantity-pickers/src/test/kotlin/com/decathlon/vitamin/compose/quantity/pickers/utils/Theme.kt
  quantity-pickers/src/test/kotlin/com/decathlon/vitamin/compose/quantity/pickers/utils/Variant.kt
  quantity-pickers/src/test/snapshots/images/com.decathlon.vitamin.compose.quantity.pickers_VitaminQuantityPickersPrimaryTest_primaryExpended[Primary,Dark].png
  quantity-pickers/src/test/snapshots/images/com.decathlon.vitamin.compose.quantity.pickers_VitaminQuantityPickersPrimaryTest_primaryExpended[Primary,Light].png
  quantity-pickers/src/test/snapshots/images/com.decathlon.vitamin.compose.quantity.pickers_VitaminQuantityPickersPrimaryTest_primary[Primary,Dark].png
  quantity-pickers/src/test/snapshots/images/com.decathlon.vitamin.compose.quantity.pickers_VitaminQuantityPickersPrimaryTest_primary[Primary,Light].png
  sample/src/main/java/com/decathlon/compose/sample/screens/QuantityPicker.kt
Labels: enhancement 🚀

#134 feat: update icons
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/__VitaminIcons.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/__Fill.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/__Line.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/fill/HearingImpairment.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/line/HearingImpairment.kt
Labels: enhancement 🚀, icons ✨, run 💨

#137 chore: delete useless label in GitHub Actions
  .github/workflows/build-pr.yml
Labels: config 🛠, icons ✨, assets 🏞

#135 feat: update assets
  foundation/foundation-assets/src/main/kotlin/com/decathlon/vitamin/compose/__VitaminAssets.kt
  foundation/foundation-assets/src/main/kotlin/com/decathlon/vitamin/compose/vitaminassets/__Shipping.kt
  foundation/foundation-assets/src/main/kotlin/com/decathlon/vitamin/compose/vitaminassets/flags/Mo.kt
  foundation/foundation-assets/src/main/kotlin/com/decathlon/vitamin/compose/vitaminassets/flags/Ne.kt
  foundation/foundation-assets/src/main/kotlin/com/decathlon/vitamin/compose/vitaminassets/flags/Tz.kt
  foundation/foundation-assets/src/main/kotlin/com/decathlon/vitamin/compose/vitaminassets/shipping/Colissimo.kt
  foundation/foundation-assets/src/main/kotlin/com/decathlon/vitamin/compose/vitaminassets/shipping/MondialRelay.kt
Labels: enhancement 🚀, assets 🏞

#132 chore(prices): add paparazzi tests
  prices/build.gradle.kts
  prices/src/test/kotlin/com/decathlon/vitamin/compose/prices/VitaminPricesPrimaryTest.kt
  prices/src/test/kotlin/com/decathlon/vitamin/compose/prices/utils/PriceVariantsFactory.kt
  prices/src/test/kotlin/com/decathlon/vitamin/compose/prices/utils/Theme.kt
  prices/src/test/kotlin/com/decathlon/vitamin/compose/prices/utils/Variant.kt
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_large[Accent,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_large[Accent,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_large[Alert,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_large[Alert,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_large[Default,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_large[Default,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_large[Strikethrough,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_large[Strikethrough,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_medium[Accent,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_medium[Accent,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_medium[Alert,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_medium[Alert,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_medium[Default,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_medium[Default,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_medium[Strikethrough,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_medium[Strikethrough,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_small[Accent,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_small[Accent,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_small[Alert,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_small[Alert,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_small[Default,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_small[Default,Light].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_small[Strikethrough,Dark].png
  prices/src/test/snapshots/images/com.decathlon.vitamin.compose.prices_VitaminPricesPrimaryTest_small[Strikethrough,Light].png
Labels: enhancement 🚀

#131 chore(snackbars): add paparazzi tests
  snackbars/build.gradle.kts
  snackbars/src/test/kotlin/com/decathlon/vitamin/compose/snackbars/VitaminSnackbarPrimaryTest.kt
  snackbars/src/test/kotlin/com/decathlon/vitamin/compose/snackbars/utils/SnackbarVariantsFactory.kt
  snackbars/src/test/kotlin/com/decathlon/vitamin/compose/snackbars/utils/Theme.kt
  snackbars/src/test/kotlin/com/decathlon/vitamin/compose/snackbars/utils/Variant.kt
  snackbars/src/test/snapshots/images/com.decathlon.vitamin.compose.snackbars_VitaminSnackbarPrimaryTest_medium[Primary,Dark].png
  snackbars/src/test/snapshots/images/com.decathlon.vitamin.compose.snackbars_VitaminSnackbarPrimaryTest_medium[Primary,Light].png
Labels: enhancement 🚀
