Repository Decathlon/vitamin-compose, pull requests merged in 2023-03, with the labels that each got.

#114 feat(sample): Add icons into Sample
  sample/src/main/java/com/decathlon/compose/sample/DashboardScreen.kt
  sample/src/main/java/com/decathlon/compose/sample/MainActivity.kt
  sample/src/main/java/com/decathlon/compose/sample/components/ResourcesScreen.kt
  sample/src/main/java/com/decathlon/compose/sample/components/SampleScaffold.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/AppBars.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Assets.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Badges.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Buttons.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Checkboxes.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Chips.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Dividers.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Fabs.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Icons.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Modals.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Prices.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Progress.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/QuantityPicker.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/RadioButtons.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Ratings.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Screen.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Skeletons.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Snackbars.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Switches.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Tabs.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Tags.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/TextInputs.kt
  settings.gradle.kts
Labels: icons ✨, build 🏗

#98 feat(Card): add card component
  cards/.gitignore
  cards/README.md
  cards/build.gradle.kts
  cards/gradle.properties
  cards/src/main/AndroidManifest.xml
  cards/src/main/java/com/decathlon/vitamin/compose/cards/VitaminCardColors.kt
  cards/src/main/java/com/decathlon/vitamin/compose/cards/VitaminCardSizes.kt
  cards/src/main/java/com/decathlon/vitamin/compose/cards/VitaminCards.kt
  cards/src/test/kotlin/com/decathlon/vitamin/compose/cards/utils/Theme.kt
  cards/src/test/kotlin/com/decathlon/vitamin/compose/cards/utils/VitaminCardsPrimaryTest.kt
  cards/src/test/snapshots/images/com.decathlon.vitamin.compose.cards.utils_VitaminCardsPrimaryTest_medium[Dark].png
  cards/src/test/snapshots/images/com.decathlon.vitamin.compose.cards.utils_VitaminCardsPrimaryTest_medium[Light].png
  sample/src/main/java/com/decathlon/compose/sample/MainActivity.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Cards.kt
  settings.gradle.kts
  vitamin/build.gradle.kts
Labels: enhancement 🚀, run 💨

#125 feat: update icons
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/__Fill.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/__Line.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/fill/Accessibility.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/fill/Keyboard.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/fill/WifiOff.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/fill/WifiOn.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/line/Accessibility.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/line/Keyboard.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/line/WifiOff.kt
  foundation/foundation-icons/src/main/kotlin/com/decathlon/vitamin/compose/vitaminicons/line/WifiOn.kt
Labels: enhancement 🚀, icons ✨, run 💨

#126 docs: add important note
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_component_request.md
  README.md
Labels: documentation 📚, run 💨

#123 chore(text-inputs): add paparazzi tests
  text-inputs/build.gradle.kts
  text-inputs/src/main/java/com/decathlon/vitamin/compose/textinputs/VitaminTextInputs.kt
  text-inputs/src/test/kotlin/com/decathlon/vitamin/compose/textinputs/VitaminTextInputsPrimaryTest.kt
  text-inputs/src/test/kotlin/com/decathlon/vitamin/compose/textinputs/utils/TextInputVariantsFactory.kt
  text-inputs/src/test/kotlin/com/decathlon/vitamin/compose/textinputs/utils/Theme.kt
  text-inputs/src/test/kotlin/com/decathlon/vitamin/compose/textinputs/utils/Variant.kt
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_error[Filled,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_error[Filled,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_error[FilledDropdown,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_error[FilledDropdown,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_error[Outlined,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_error[Outlined,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_error[OutlinedDropdown,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_error[OutlinedDropdown,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_normal[Filled,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_normal[Filled,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_normal[FilledDropdown,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_normal[FilledDropdown,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_normal[Outlined,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_normal[Outlined,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_normal[OutlinedDropdown,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_normal[OutlinedDropdown,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_success[Filled,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_success[Filled,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_success[FilledDropdown,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_success[FilledDropdown,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_success[Outlined,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_success[Outlined,Light].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_success[OutlinedDropdown,Dark].png
  text-inputs/src/test/snapshots/images/com.decathlon.vitamin.compose.textinputs_VitaminTextInputsPrimaryTest_success[OutlinedDropdown,Light].png
Labels: enhancement 🚀, run 💨
