Repository Decathlon/vitamin-compose, pull requests merged in 2023-02, with the labels that each got.

#17 feat: add Chip component with action, filter & input variants
  chips/.gitignore
  chips/README.md
  chips/build.gradle.kts
  chips/gradle.properties
  chips/proguard-rules.pro
  chips/src/main/AndroidManifest.xml
  chips/src/main/java/com/decathlon/vitamin/compose/chips/VitaminChipButtons.kt
  chips/src/main/java/com/decathlon/vitamin/compose/chips/VitaminChipSizes.kt
  chips/src/main/java/com/decathlon/vitamin/compose/chips/VitaminChips.kt
  chips/src/main/java/com/decathlon/vitamin/compose/chips/VtmnChipColors.kt
  chips/src/main/java/com/decathlon/vitamin/compose/chips/impl/VitaminChipImpl.kt
  chips/src/main/java/com/decathlon/vitamin/compose/chips/impl/VitaminFilterChipImpl.kt
  chips/src/main/res/values-fr/strings.xml
  chips/src/main/res/values/strings.xml
  chips/src/test/kotlin/com/decathlon/vitamin/compose/chips/VitaminChipsPrimaryTest.kt
  chips/src/test/kotlin/com/decathlon/vitamin/compose/chips/utils/ChipsVariantsFactory.kt
  chips/src/test/kotlin/com/decathlon/vitamin/compose/chips/utils/Theme.kt
  chips/src/test/kotlin/com/decathlon/vitamin/compose/chips/utils/Variant.kt
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[Action,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[Action,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[Filter,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[Filter,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[Input,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[Input,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[InputWithIcon,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[InputWithIcon,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[InputWithImage,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[InputWithImage,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[SingleChoice,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_medium[SingleChoice,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[Action,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[Action,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[Filter,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[Filter,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[Input,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[Input,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[InputWithIcon,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[InputWithIcon,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[InputWithImage,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[InputWithImage,Light].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[SingleChoice,Dark].png
  chips/src/test/snapshots/images/com.decathlon.vitamin.compose.chips_VitaminChipsPrimaryTest_small[SingleChoice,Light].png
  foundation/src/main/java/com/decathlon/vitamin/compose/foundation/Ripple.kt
  sample/src/main/java/com/decathlon/compose/sample/MainActivity.kt
  sample/src/main/java/com/decathlon/compose/sample/screens/Chips.kt
  settings.gradle.kts
  vitamin/build.gradle.kts
Labels: enhancement 🚀, build 🏗

#106 fix(Badges): fix content color
  badges/src/main/java/com/decathlon/vitamin/compose/badges/internals/VitaminStandaloneBadgeImpl.kt
Labels: bug 🐛, run 💨

#107 fix(sample): Remove white background for badges in sample
  sample/src/main/java/com/decathlon/compose/sample/screens/Badges.kt
Labels: bug 🐛, run 💨

#113 build: Add plugin to check conventional commit message format
  build.gradle.kts
Labels: config 🛠, run 💨
